"""Encode unmodified Kenney PNG pixels for SDL, without a runtime PNG dependency.

Run with Pillow installed. Generated header is checked in; CI needs no Pillow.
"""
from pathlib import Path
import zlib
from PIL import Image

root = Path(__file__).resolve().parents[1] / "sorr-vita-master/cmake/ios"
lines = ['/* Generated by tools/embed_touch_art.py. Kenney Mobile Controls, CC0. */']
for name, filename in [('button', 'button_circle.png'), ('pad', 'joystick_circle_pad_a.png'), ('nub', 'joystick_circle_nub_b.png')]:
    im = Image.open(root / 'controls' / filename).convert('RGBA')
    data = zlib.compress(im.tobytes(), 9)
    lines.append(f'static const int touch_{name}_w = {im.width}, touch_{name}_h = {im.height};')
    lines.append(f'static const unsigned char touch_{name}_pixels[] = {{')
    lines.extend(','.join(str(b) for b in data[i:i+24]) + ',' for i in range(0, len(data), 24))
    lines.append('};')
(root / 'src/sorr_ios_touch_art.h').write_text('\n'.join(lines) + '\n')
